stages:
  - test
  - release

lint:
  stage: test
  # Check for updates: https://hub.docker.com/r/dshanley/vacuum/tags
  image: 
    name: dshanley/vacuum:v0.8.5@sha256:6d396c7e21aba0890ea764836f1fe8a8c629a184e2addc298492e8fa06d22392
    # Disable the default entrypoint.
    entrypoint: [""]
  script:
    # The tool used is this: https://quobix.com/vacuum/
    - vacuum lint --details request_tracker_rest2.yaml


# Make a new release when new semver tags are pushed.
release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    # Run this job when a simple semantic version tag is created.
    - if: $CI_COMMIT_TAG =~ /^[0-9]+\.[0-9]+\.[0-9]+$/
  script:
    - echo "Making a release"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG_MESSAGE'
