# -*- encoding: utf-8 -*-

=begin
#Request Tracker REST2

#Partial specification of Request Tracker's REST2 API.

The version of the OpenAPI document: 0.3.1
Contact: iihaja@utu.fi
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

$:.push File.expand_path("../lib", __FILE__)
require "rt/version"

Gem::Specification.new do |s|
  s.name        = "rt"
  s.version     = RT::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["OpenAPI-Generator"]
  s.email       = ["iihaja@utu.fi"]
  s.homepage    = "https://openapi-generator.tech"
  s.summary     = "Request Tracker REST2 Ruby Gem"
  s.description = "Partial specification of Request Tracker's REST2 API."
  s.license     = "Unlicense"
  s.required_ruby_version = ">= 2.7"
  s.metadata    = {}

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'

  s.files         = `find *`.split("\n").uniq.sort.select { |f| !f.empty? }
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
